// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5_c8aBPVoYhHapM9zXjWCG8RRctEdqH8',
    appId: '1:133401152900:web:872587820b3b6132c1e1d1',
    messagingSenderId: '133401152900',
    projectId: 'pharmacy-app-93a9a',
    authDomain: 'pharmacy-app-93a9a.firebaseapp.com',
    storageBucket: 'pharmacy-app-93a9a.appspot.com',
    measurementId: 'G-53G8V9QLPP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNH1iYIBgdbGSl3kCR6slWw3KAvsDD-J4',
    appId: '1:133401152900:android:e5ec2ba62e656b17c1e1d1',
    messagingSenderId: '133401152900',
    projectId: 'pharmacy-app-93a9a',
    storageBucket: 'pharmacy-app-93a9a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7jytg7MewDIY3Li1uCeglQm8zpzCHziU',
    appId: '1:133401152900:ios:3f24016abb44d1c5c1e1d1',
    messagingSenderId: '133401152900',
    projectId: 'pharmacy-app-93a9a',
    storageBucket: 'pharmacy-app-93a9a.appspot.com',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7jytg7MewDIY3Li1uCeglQm8zpzCHziU',
    appId: '1:133401152900:ios:e26ce84b8cde6c24c1e1d1',
    messagingSenderId: '133401152900',
    projectId: 'pharmacy-app-93a9a',
    storageBucket: 'pharmacy-app-93a9a.appspot.com',
    iosBundleId: 'com.example.flutterApplication2.RunnerTests',
  );
}
