import 'package:get/get.dart';

class Local implements Translations {
  @override
  // TODO: implement keys
  Map<String, Map<String, String>> get keys => {
        'ar': {
          "titleHome": "داويني",
          "Oral": "شفوي",
          "External": "خارجي",
          "Injectable": "حقن",
          "Intravenous": "وريدي",
          "Vaccines": "لقاحات",
          "Sterilizers": "معقمات",
          "Other": "أخرى",
          "AllProducts": "كل المنتجات",
          "TheMostCommon": "الأكثر شيوعا",
          "RecentlyAdded": "المضافة مؤخرا",
          "OralUse": "استخدام شفوي",
          "ExternalUse": "استخدام خارجي",
          "Injectable": "حقن",
          "IntravenousFluids": "سوائل وريدية",
          "Vaccines&Serums": "لقاحات وأمصال",
          "Sterilizers": "معقمات",
          "Other": "أخرى",
          "ViewAll": "عرض الكل",
          "oral_use": "استخدام شفوي",
          "external_use": "استخدام خارجي",
          "injectable": "حقن",
          "Intravenous_fluids": "سوائل وريدية",
          "vaccines_and_serums": "لقاحات وأمصال",
          "sterilizers": "معقمات",
          "other": "أخرى",
          "About": "حول",
          "AddToCart": "اضف الى السلة",
          "CheckOut": "خروج",
          "PaymentSummary": "ملخص الدفع",
          "Totalprice": "السعر الكلي",
          "Submit": "تأكيد",
          "MyCart": "السلة",
          "FavoritesisEmpty": "المفضلة فارغة",
          "LetsGotoProductsPage":
              "دعنا نذهب إلى صفحة المنتجات حيث يمكنك رؤية جميع المنتجات وإضافتها إلى المفضلة",
          "Favorites": "المفضلة",
          "MyOrder": "طلباتي",
          "Details": "التفاصيل",
          "ItemsCount": "عدد العناصر",
          "Sending": "يتم الإرسال",
          "Received": "مستلم",
          "Pending": "يتم التحضير",
          "OrderDetails": "تفاصيل الطلب",
          "OrderPlaced": "تم الطلب",
          "YourOrderisPreapring": "طلبك قيد التحضير",
          "OrderSending": "الطلب قيد الإرسال",
          "YourOrderIsInThewaytoYou": "طلبك في الطريق إليك",
          "OrderReceived": "الطلب مستلم",
          "OrderHasBeenrecived": "تم استلام الطلب",
          "Phonenumber": "رقم الموبايل",
          "Password": "كلمة المرور",
          "SIGNIN": "تسجيل الدخول",
          "HAVEANACCOUNT": "ليس لديك حساب؟ ",
          "SIGNUP": "انشئ حساب",
          "Name": "اسم",
          "Email": "بريد إلكتروني",
          "ConfirmPassword": "تأكيد كلمة المرور",
          "CREATEANACCOUNT": "إنشاء حساب",
          "ALREADYHAVEANACCOUNT": "هل لديك حساب؟"
        },
        'en': {
          "titleHome": "Dawiny",
          "Oral": "Oral",
          "External": "External",
          "Injectable": "Injectable",
          "Intravenous": "Intravenous",
          "Vaccines": "Vaccines",
          "Sterilizers": "Sterilizers",
          "Other": "Other",
          "AllProducts": "All Products",
          "TheMostCommon": "The Most Common",
          "RecentlyAdded": "Recently Added",
          "OralUse": "Oral Use",
          "ExternalUse": "External Use",
          "Injectable": "Injectable",
          "IntravenousFluids": "Intravenous Fluids",
          "Vaccines&Serums": "Vaccines & Serums",
          "Sterilizers": "Sterilizers",
          "Other": "Other",
          "ViewAll": "View All",
          "oral_use": "oral_use",
          "external_use": "external_use",
          "injectable": "injectable",
          "Intravenous_fluids": "Intravenous_fluids",
          "vaccines_and_serums": "vaccines_and_serums",
          "sterilizers": "sterilizers",
          "other": "other",
          "About": "About",
          "AddToCart": "AddToCart",
          "CheckOut": "Check Out",
          "PaymentSummary": "Payment Summary",
          "Totalprice": "Total price",
          "Submit": "Submit",
          "MyCart": "My Cart",
          "FavoritesisEmpty": "Favorites is Empty",
          "LetsGotoProductsPage":
              "Lets Go to Products Page Where You Can See All Product And Add To Favorite What You Like",
          "Favorites": "Favorites",
          "MyOrder": "My Order",
          "Details": "Details",
          "ItemsCount": "Items Count",
          "Sending": "Sending",
          "Received": "Received",
          "Pending": "Pending",
          "OrderDetails": "Order Details",
          "OrderPlaced": "Order Placed",
          "YourOrderisPreapring": "Your Order is Preapring",
          "OrderSending": "Order Sending",
          "YourOrderIsInThewaytoYou": "Your Order Is In The way to You",
          "OrderReceived": "Order Received",
          "OrderHasBeenrecived": "Order Has Been recived",
          "Phonenumber": "Phone number",
          "Password": "Password",
          "SIGNIN": "SIGN IN",
          "HAVEANACCOUNT": "DON'T HAVE AN ACCOUNT? ",
          "SIGNUP": "SIGN UP ",
          "Name": "Name",
          "Email": "Email",
          "ConfirmPassword": "Confirm Password",
          "CREATEANACCOUNT": "CREATE AN ACCOUNT",
          "ALREADYHAVEANACCOUNT": "ALREADY HAVE AN ACCOUNT? "
        }
      };
}
